# Generated by Django 5.0.4 on 2024-04-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='extention',
            field=models.CharField(max_length=10, null=True, verbose_name='photo_extension'),
        ),
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
