# Generated by Django 5.0.4 on 2024-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_photo_extention_photo_height_photo_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='photos', to='admin_app.tag'),
        ),
    ]
