# Generated by Django 5.0.4 on 2024-04-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_photo_extention_alter_photo_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
